"use client";

const TESTIMONIALS = [
  {
    quote: "TEOS replaced our entire content team workflow. We generate 30 posts a week across 5 platforms in under an hour. The visibility scores are genuinely predictive.",
    name: "Ahmed Hassan",
    role: "Founder, GrowthCo Egypt",
    avatar: "AH",
    color: "#C9A84C",
  },
  {
    quote: "As a solo consultant managing 8 client brands, TEOS is the only tool that handles my entire content calendar. The Egyptian sovereign infrastructure means my clients' data stays safe.",
    name: "Sara El-Sayed",
    role: "Independent Brand Strategist",
    avatar: "SE",
    color: "#00bfa5",
  },
  {
    quote: "The platform-specific optimization is unlike anything else. A LinkedIn post generated by TEOS performs 3x better than what I used to write manually. Worth every penny.",
    name: "Omar Khalil",
    role: "Marketing Director, TechMENA",
    avatar: "OK",
    color: "#8b5cf6",
  },
];

const LOGO_BRANDS = ["Startup Egypt", "ITIDA", "GrowthCo", "TechMENA", "Pi Network"];

export default function Testimonials() {
  return (
    <section className="section-padding relative overflow-hidden">
      <div
        className="hero-glow"
        style={{ background: "rgba(201,168,76,0.08)", top: "20%", right: "-200px" }}
      />

      <div className="section-container relative z-10">
        {/* Header */}
        <div className="mx-auto max-w-2xl text-center mb-16">
          <span className="section-label">Testimonials</span>
          <h2
            className="text-4xl md:text-5xl lg:text-6xl mb-5 leading-tight"
            style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontWeight: 600 }}
          >
            Trusted by{" "}
            <span className="gradient-gold">Egypt&apos;s builders</span>
          </h2>
          <p className="text-[#8a88a0] text-lg">
            From solo founders to agencies managing 10+ brands — TEOS scales with you.
          </p>
        </div>

        {/* Testimonial Cards */}
        <div className="grid md:grid-cols-3 gap-6 mb-16">
          {TESTIMONIALS.map((item, i) => (
            <div
              key={i}
              className="relative rounded-2xl p-7 flex flex-col"
              style={{
                background: "#111118",
                border: "1px solid rgba(255,255,255,0.05)",
                transition: "all 0.3s ease",
              }}
              onMouseEnter={e => {
                const el = e.currentTarget;
                const alpha = item.color === "#C9A84C" ? "201,168,76" : item.color === "#00bfa5" ? "0,191,165" : "139,92,246";
                el.style.borderColor = `rgba(${alpha},0.2)`;
                el.style.transform = "translateY(-4px)";
                el.style.boxShadow = "0 20px 60px rgba(0,0,0,0.4)";
              }}
              onMouseLeave={e => {
                const el = e.currentTarget;
                el.style.borderColor = "rgba(255,255,255,0.05)";
                el.style.transform = "translateY(0)";
                el.style.boxShadow = "none";
              }}
            >
              {/* Quote mark */}
              <div
                className="text-5xl leading-none mb-4 select-none"
                style={{
                  color: item.color,
                  opacity: 0.35,
                  fontFamily: "'Crimson Pro', Georgia, serif",
                  lineHeight: 1,
                }}
              >
                &ldquo;
              </div>

              <p
                className="text-[#e8e6f0] flex-1 mb-6"
                style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: "1.05rem", lineHeight: 1.7 }}
              >
                {item.quote}
              </p>

              <div className="flex items-center gap-3">
                <div
                  className="flex h-9 w-9 items-center justify-center rounded-full text-xs font-bold shrink-0"
                  style={{
                    background: `${item.color}18`,
                    border: `1px solid ${item.color}44`,
                    color: item.color,
                    fontFamily: "'Space Mono', monospace",
                  }}
                >
                  {item.avatar}
                </div>
                <div>
                  <div className="text-sm font-semibold" style={{ color: "#e8e6f0" }}>
                    {item.name}
                  </div>
                  <div className="text-xs" style={{ color: "#8a88a0" }}>
                    {item.role}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Logo Bar */}
        <div className="text-center">
          <p
            className="text-xs mb-6"
            style={{ fontFamily: "'Space Mono', monospace", color: "rgba(255,255,255,0.2)", letterSpacing: "0.12em" }}
          >
            TRUSTED BY TEAMS AT
          </p>
          <div className="flex flex-wrap items-center justify-center gap-8">
            {LOGO_BRANDS.map(brand => (
              <span
                key={brand}
                className="text-sm font-semibold"
                style={{ color: "rgba(255,255,255,0.15)" }}
              >
                {brand}
              </span>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
